version: '3.8'
services:
#1. httpd -> apache for mock website http://shanghai3721.ml/httpd/
#--> Working
    httpd:
        build:
            dockerfile: Dockerfile
            context: ./httpd
        container_name: httpd
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 80
        volumes: 
            - ./conf.d/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - net
#2. Nginx -> proxy server
#--> Working
# listen 80, 31300 --> Mock website https://shanghai3721.ml
# proxy pass
# /grafana/ --> proxy_pass http://grafana:3000/;
# /httpd/ --> proxy_pass http://httpd:80/;
# /portainer/ --> proxy_pass http://portainer:9000/;
# /jenkins/ --> proxy_pass http://jenkins:8080/jenkins/;
# /tomcat/ --> proxy_pass http://tomcat:8080/;
# /adminer/ --> proxy_pass http://adminer:8080/;
    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
        volumes: 
            - ./conf.d/nginx/conf.d:/etc/nginx/conf.d
            - ./conf.d/nginx/html:/usr/share/nginx/html
            - ./conf.d/nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./conf.d/nginx/nginx_logs:/var/log/nginx
            - ./conf.d/nginx/web_logs:/etc/nginx/logs
            - ./conf.d/tls:/etc/nginx/ssl
        networks: 
            - net
#3. trojan go -> fuck GFW
#--> Working
    trojan-go:
        build:
            dockerfile: Dockerfile
            context: ./trojan-go
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 31296
        volumes:
            - ./conf.d/trojan-go:/etc/trojan-go
        networks: 
            - net
#        depends_on:
#            - nginx
#4. xray -> fuck GFW * Proxy Server
# VLESS_XTLS/TLS-direct_TCP
# VLESS_WS
#--> Working
    xray:
        build:
            dockerfile: Dockerfile
            context: ./xray
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
        volumes: 
            - ./conf.d/xray:/etc/xray
        networks: 
            - net
#        depends_on:
#            - nginx
#5. v2ray -> fuck GFW
#--> NOT working
    v2ray:
        build:
            dockerfile: Dockerfile
            context: ./v2ray
        container_name: v2ray
        restart: always
        environment: 
            TZ: Asia/Shanghai
#            TARGETPLATFORM: linux/amd64
#            TAG: 'v4.39.2'
        expose: 
            - 1080
        volumes: 
            - ./conf.d/v2ray:/etc/v2ray
        networks: 
            - net
#        depends_on:
#            - nginx
#6. prometheus -> monitor virtual machines
#--> Working
    prometheus:
        build:
            dockerfile: Dockerfile
            context: ./prometheus
        container_name: prometheus
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 9090
        volumes:
            - ./conf.d/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
            - ./conf.d/prometheus/groups/:/root/prometheus/groups/
            - ./conf.d/prometheus/groups/:/usr/local/prometheus/groups/ 
            - ./conf.d/prometheus/rules/:/root/prometheus/rules/
            - ./conf.d/prometheus/groups/:/usr/local/prometheus/rules/ 
        networks: 
            - net
#7. alertmanager -> alter users
#--> NOT working
    alertmanager:
        build:
            dockerfile: Dockerfile
            context: ./alertmanager
        container_name: alertmanager
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 9093
        volumes:
            - ./conf.d/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        networks: 
            - net
#8. grafana -> monitor UI
#--> Working
    grafana:
        build:
            dockerfile: Dockerfile
            context: ./grafana
        container_name: grafana
        restart: always
        environment: 
        #https://grafana.com/docs/grafana/latest/administration/configuration/
        #GF_<SectionName>_<KeyName>
            TZ: Asia/Shanghai
        #    GF_PATHS_CONFIG: /etc/grafana/grafana.ini
        #    GF_PATHS_DATA: /var/lib/grafana
        #    GF_PATHS_HOME: /usr/share/grafana
        #    GF_PATHS_LOGS: /var/log/grafana
        #    GF_PATHS_PLUGINS: /var/lib/grafana/plugins
        #    GF_PATHS_PROVISIONING: /etc/grafana/provisioning
        #    GF_SERVER_PROTOCOL: https
            GF_SERVER_PROTOCOL: http
            GF_SERVER_HTTP_PORT: 3000
            GF_SERVER_DOMAIN: shanghai3721.ml
            GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
            GF_SERVER_SERVE_FROM_SUB_PATH: "true"
        #    GF_SECURITY_ADMIN_PASSWORD: etL#flk*r4KDo$32Ulfe$%3

            GF_SERVER_ENABLE_GZIP: 'true'
            GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
            GF_USERS_ALLOW_SIGN_UP: 'true'
            GF_USERS_VIEWERS_CAN_EDIT: 'true'
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
            GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
            GF_ANALYTICS_REPORTING_ENABLED: 'false'
            GF_ANALYTICS_CHECK_FOR_UPDATES: 'false'
            ROUSER: ocean  # read-only user name for postgres
            ROPASSWORD__FILE: /run/secrets/postgres_ro_password  # postgres read-only user password
            
        #    GF_SERVER_CERT_FILE: /etc/grafana/shanghai3721.ml.crt
        #    GF_SERVER_CERT_KEY: /etc/grafana/shanghai3721.ml.key
        secrets:
            - grafana_admin_password
            - postgres_ro_password
        volumes:
            - ./conf.d/grafana/:/etc/grafana/
            # 持久化配置文件
            - grafana-storage:/var/lib/grafana 
#            - ./conf.d/grafana/data/:/var/lib/grafana/

#            - grafana-config:/etc/grafana
        expose:
            - 3000
        networks: 
            - net
#9. cadvisor -> container advisor / monitor  
#--> Working      
    cadvisor:
        build:
            dockerfile: Dockerfile
            context: ./cadvisor
        container_name: cadvisor
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 8080
        volumes:
            - /:/rootfs
            - /var/run:/var/run
            - /sys:/sys
            - /var/lib/docker/:/var/lib/docker
            - /dev/disk/:/dev/disk
        networks: 
            - net
#10. Jenkins -> CI/CD
#--> Working
    jenkins:
        build:
            dockerfile: Dockerfile
            context: ./jenkins
        container_name: jenkins
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 8088:8080
        expose: 
            - 50000
        volumes:
            - ./jenkins/jenkins_home:/var/jenkins_home
        networks: 
            - net        
#11. Portainer -> Docker UI
#--> Working
    portainer:
        build:
            dockerfile: Dockerfile
            context: ./portainer
        container_name: portainer
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 8000
            - 9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks: 
            - net     
#12. Tomcat -> JSP Server
#--> NOT working
    tomcat:
        build:
            dockerfile: Dockerfile
            context: ./tomcat
        container_name: tomcat
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 8080
        networks: 
            - net
#13. mysql ->  Relational Database
#--> Working
    mysql:
        build:
            dockerfile: Dockerfile
            context: ./mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            TZ: Asia/Shanghai
            # root
            MYSQL_ROOT_PASSWORD: ABC123abc
        networks: 
            - net
#14. Adminer -> Database UI
#--> Working
    adminer:
        build:
            dockerfile: Dockerfile
            context: ./adminer
        container_name: adminer
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 8080
        networks: 
            - net
#15. GitLab -> source code control
#--> Unknown
    gitlab:
        build:
            dockerfile: Dockerfile
            context: ./gitlab
        container_name: gitlab
        restart: always
        volumes:
        # For storing application data.
          - $GITLAB_HOME/data:/var/opt/gitlab
        # For storing logs.
          - $GITLAB_HOME/logs:/var/log/gitlab
        # For storing the GitLab configuration files.
          - $GITLAB_HOME/config:/etc/gitlab
        restart: always
        environment:
        # Add any other gitlab.rb configuration here, each on its own line
            GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
        configs:
          - source: gitlab
            target: /omnibus_config.rb
        secrets:
          - gitlab_root_password
        expose:
          - 22
          - 80
          - 443
        networks: 
          - net        
#    gitlab-runner:
#        image: gitlab/gitlab-runner:alpine
#        deploy:
#            mode: replicated
#        replicas: 4
#        networks: 
#            - net      
configs:
  gitlab:
    file: ./gitlab.rb

networks: 
    net:
        driver: bridge

volumes:
    grafana-storage:
#    external: true
    portainer_data:
#  grafana-config:
#    external: true

secrets:
    grafana_admin_password:
        file: ./secrets/grafana_admin_password.txt
    postgres_postgres_password:
        file: ./secrets/postgres_postgres_password.txt
    postgres_ro_password:
        file: ./secrets/postgres_ro_password.txt
    gitlab_root_password:
        file: ./secrets/root_password.txt