version: '3.8'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 9090:9090
        volumes:
            - /home/linfengzhong/git/repos/toolbox/Docker/docker-compose/prometheus-grafana/prometheus.yml:/etc/prometheus/prometheus.yml 
        networks: 
            - monitor-net

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 3000:3000
        networks: 
            - monitor-net
        
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 8080:8080
        volumes:
            - /:/rootfs
            - /var/run:/var/run
            - /sys:/sys
            - /var/lib/docker/:/var/lib/docker
            - /dev/disk/:/dev/disk
        networks: 
            - monitor-net
        
networks: 
    monitor-net:
        driver: bridge