version: '3.8'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 9090:9090
        volumes:
            - ~/prometheus.yml:/etc/prometheus/prometheus.yml 
            - ~/groups/:/root/prometheus/groups/:/usr/local/prometheus/groups/ 
            - ~/rules/:/root/prometheus/rules/:/usr/local/prometheus/rules/ 
        networks: 
            - monitor-net

    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 9093:9093
        volumes:
            - ~/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        networks: 
            - monitor-net

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 3000:3000
        networks: 
            - monitor-net
        
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 8080:8080
        volumes:
            - /:/rootfs
            - /var/run:/var/run
            - /sys:/sys
            - /var/lib/docker/:/var/lib/docker
            - /dev/disk/:/dev/disk
        networks: 
            - monitor-net
        
networks: 
    monitor-net:
        driver: bridge