# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/tomcat
# https://github.com/docker-library/tomcat

FROM tomcat:10.0.7-jdk16-openjdk-buster
LABEL maintainer="Fred <fred.zhong@outlook.com>"