# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/jenkins
# https://github.com/jenkinsci/docker
# https://plugins.jenkins.io/cloudbees-folder/

FROM jenkins:2.60.3-alpine
LABEL maintainer="Fred <fred.zhong@outlook.com>"