version: '3.1'
services:

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
        expose:
            - 31300 
        volumes: 
            - ./conf.d/nginx/conf.d:/etc/nginx/conf.d
            - ./conf.d/nginx/html:/usr/share/nginx/html
            - ./conf.d/nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./conf.d/nginx/nginx_logs:/var/log/nginx
            - ./conf.d/nginx/web_logs:/etc/nginx/logs
            - ./conf.d/tls:/etc/nginx/ssl
        networks: 
            - xray-net
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    xray:
        build:
            dockerfile: Dockerfile
            context: ./Dockerfile/Xray-Alpine
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
        expose:
            - 31297
            - 31298
            - 31299
            - 31301
        volumes: 
            - ./conf.d/xray:/etc/xray
            - ./conf.d/tls:/etc/xray/tls
        networks: 
            - xray-net
            
    trojan-go:
        image: trojan-go:latest
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 31296
        volumes:
            - ./conf.d/trojan-go:/etc/trojan-go
        networks: 
            - xray-net
        
networks: 
    xray-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.18.0/16
                  gateway: 172.18.18.1 
                  aux_addresses:
                    nginx: 172.18.18.2
                    xray: 172.18.18.3
                    trojan-go: 172.18.18.4