version: '3.1'
services: 
    xray:
        build:
            dockerfile: Dockerfile
            context: ./Dockerfile/Xray-Alpine
            labels: xray:latest
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
        expose:
            - 31297
            - 31298
            - 31299
            - 31301
        volumes: 
            - ./xray:/etc/xray
            - ./xray/log:/etc/xray/log
            - ./tls:/home/root/cert
        networks: 
            - xray-net

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
        expose:
            - 31300 
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./nginx/nginx_logs:/var/log/nginx
            - ./nginx/web_logs:/etc/nginx/logs
            - ./tls:/etc/nginx/ssl
        networks: 
            - xray-net

    trojan-go:
        image: trojan-go:latest
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 31296
        volumes:
            - ./trojan:/etc/v2ray-agent/trojan/
            - ./trojan:/etc/trojan-go
        networks: 
            - xray-net
        
networks: 
    xray-net:
        driver: bridge
        ipam:
            config:
                subnet: 172.18.18.0/16
                gateway: 172.18.18.1
                aux_addresses:
                    nginx: 172.18.18.2
                    xray: 172.18.18.3
                    trojan-go: 172.18.18.4