# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/mysql
# https://github.com/docker-library/mysql

FROM mysql:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"