version: '3.4'
services:

    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
        volumes: 
            - ./conf.d/nginx/conf.d:/etc/nginx/conf.d
            - ./conf.d/nginx/html:/usr/share/nginx/html
            - ./conf.d/nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./conf.d/nginx/nginx_logs:/var/log/nginx
            - ./conf.d/nginx/web_logs:/etc/nginx/logs
            - ./conf.d/tls:/etc/nginx/ssl
        networks: 
            - xray-net
            
    trojan-go:
        build:
            dockerfile: Dockerfile
            context: ./trojan-go
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 443:443
        volumes:
            - ./conf.d/trojan-go:/etc/trojan-go
        networks: 
            - xray-net
        
networks: 
    xray-net:
        driver: bridge