# Dockerfile for Maven based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/maven
# 

FROM maven:3.8.1-openjdk-15
LABEL maintainer="Fred <fred.zhong@outlook.com>"