# Dockerfile for Nginx based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/nginx
# https://www.nginx.com

FROM nginx:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"