version: '3'
services: 
    xray:
        image: xray:latest
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
            - 127.0.0.1:31297:31297
            - 127.0.0.1:31298:31298
            - 127.0.0.1:31299:31299
            - 127.0.0.1:31301:31301
        volumes: 
            - ./xray/conf.d:/etc/xray/conf.d
            - ./xray/log:/etc/v2ray-agent/xray
            - ./tls:/home/root/cert
        networks: 
            - dockernet

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
            - 127.0.0.1:31300:31300
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./nginx/nginx_logs:/var/log/nginx
            - ./nginx/web_logs:/etc/nginx/logs
            - ./tls:/etc/nginx/ssl
        networks: 
            - dockernet

    trojan-go:
        image: trojan-go:latest
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 127.0.0.1:31296:31296
        volumes:
            - ./trojan:/etc/v2ray-agent/trojan/
            - ./trojan:/etc/trojan-go
        networks: 
            - dockernet
        
networks: 
    dockernet: