# Dockerfile for acem based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://github.com/acmesh-official/acme.sh
# https://github.com/acmesh-official/acme.sh/wiki/Run-acme.sh-in-docker
# https://github.com/acmesh-official/acme.sh/wiki/deploy-to-docker-containers

FROM neilpang/acme.sh:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"