version: '3.8'
services:
#1. httpd -> apache for mock website http://shanghai3721.ml/httpd/
#--> Working
    httpd:
        image: httpd:alpine
        container_name: httpd
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 80
        volumes: 
            - ./httpd/html6/:/usr/local/apache2/htdocs/
            - ./httpd/conf/:/usr/local/apache2/conf/
        networks:
            - net
#2. Nginx -> proxy server
#--> Working
# listen 80, 31300 --> Mock website https://shanghai3721.ml
# proxy pass
# /grafana/ --> proxy_pass http://grafana:3000/;
# /httpd/ --> proxy_pass http://httpd:80/;
# /portainer/ --> proxy_pass http://portainer:9000/;
# /jenkins/ --> proxy_pass http://jenkins:8080/jenkins/;
# /tomcat/ --> proxy_pass http://tomcat:8080/;
# /adminer/ --> proxy_pass http://adminer:8080/;
    nginx:
        image: nginx:alpine
        container_name: nginx
        labels:
            - sh.acme.autoload.domain=k8s-master.ml
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 31300
        ports:
            - 80:80
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/error.log:/var/log/nginx/error.log
            - ./nginx/access.log:/var/log/nginx/access.log
        networks: 
            - net
#3. trojan go -> fuck GFW
#--> Working
    trojan-go:
        image: p4gefau1t/trojan-go:latest
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose:
            - 31296
        volumes:
            - ./trojan-go:/etc/trojan-go
        networks: 
            - net
#        depends_on:
#            - nginx
#4. xray -> fuck GFW * Proxy Server
# VLESS_XTLS/TLS-direct_TCP
# VLESS_WS
#--> Working
    xray:
        image: teddysun/xray:latest
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
        volumes: 
            - ./xray:/etc/xray
        networks: 
            - net
#        depends_on:
#            - nginx
#11. Portainer -> Docker UI
#--> Working
    portainer:
        image: portainer/portainer-ce:alpine
        container_name: portainer
        restart: always
        environment: 
            TZ: Asia/Shanghai
        expose: 
            - 8000
            - 9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/data:/data
        networks: 
            - net     

networks: 
    net:
        driver: bridge