# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/_/adminer
# https://github.com/TimWolla/docker-adminer

FROM adminer:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"