# Dockerfile for grafana based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/grafana/grafana
# https://grafana.com

FROM grafana/grafana:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"

#COPY ./data/ /var/lib/grafana/

#RUN sudo chmod -R 777 /var/lib/grafana/

#USER grafana
#WORKDIR /
#ENTRYPOINT [ "/run.sh" ]