# Dockerfile for grafana based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/grafana/grafana
# https://grafana.com
# Docker(Alpine base image)
# Lightweight Docker container image using an Alpine base image.
# docker run -d --name=grafana -p 3000:3000 grafana/grafana
# Note: If you are on a Linux system, you might need to add sudo before the command.

FROM grafana/grafana:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"

#COPY ./data/ /var/lib/grafana/

#RUN sudo chmod -R 777 /var/lib/grafana/

#USER grafana
#WORKDIR /
#ENTRYPOINT [ "/run.sh" ]