# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/gitlab/gitlab-ce
# https://about.gitlab.com/get-help/

FROM gitlab/gitlab-ce:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"