# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/portainer/portainer-ce
# https://documentation.portainer.io/quickstart

FROM portainer/portainer-ce:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"