run-type: server
local-addr: trojan-go
local-port: 443
remote-addr: nginx
remote-port: 80
password:
  - ead3ae26-e2f2-46ef-9e38-1929fd1ea662
ssl:
  cert: /etc/trojan-go/tls/shanghai3721.ml.crt
  key: /etc/trojan-go/tls/shanghai3721.ml.key
  sni: shanghai3721.ml
router:
  enabled: true
  block:
    - 'geoip:private'
  geoip: /etc/trojan-go/geoip.dat
  geosite: /etc/trojan-go/geosite.dat