version: '3'
services: 
    xray:
        image: teddysun/xray
        container_name: xray
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports: 
            - 443:443
            - 31297:31297
            - 31298:31298
            - 31299:31299
            - 31301:31301
        volumes: 
            - ./v2ray-agent/xray/conf:/etc/xray
            - ./v2ray-agent/xray/log/error.log:/etc/v2ray-agent/xray/error.log
            - ./v2ray-agent/tls:/home/root/cert
        networks: 
            - dockernet

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 80:80
            - 31300:31300
        volumes: 
            - ./v2ray-agent/nginx/conf.d:/etc/nginx/conf.d
            - ./v2ray-agent/nginx/html:/usr/share/nginx/html
            - ./v2ray-agent/nginx/subscribe:/etc/v2ray-agent/subscribe
            - ./v2ray-agent/nginx/nginx_logs:/var/log/nginx
            - ./v2ray-agent/nginx/web_logs:/etc/nginx/logs
            - ./v2ray-agent/tls:/etc/nginx/ssl
        networks: 
            - dockernet

    trojan-go:
        image: teddysun/trojan-go:latest
        container_name: trojan-go
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - 31296:31296
        volumes:
            - ./v2ray-agent/trojan:/etc/v2ray-agent/trojan/trojan.log
        networks: 
            - dockernet
        
networks: 
    dockernet: