# Dockerfile for cAdvisor based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/google/cadvisor

FROM google/cadvisor:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"