# Dockerfile for prometheus based alpine
# Copyright (C) 2019 - 2021 Fred <fred.zhong@outlook.com>
# Reference URL:
# https://hub.docker.com/r/prom/prometheus
# https://github.com/prometheus/prometheus

FROM prom/prometheus:latest
LABEL maintainer="Fred <fred.zhong@outlook.com>"